---
title: "Hello R"
author: "Marlene Berrios"
date: "Data 2401"
output: 
  html_document: 
    fig_width: 14
    fig_height: 10
    highlight: zenburn
    theme: sandstone
---

MAKE SURE YOU READ AND FOLLOW **ALL** INSTRUCTIONS ON THE INSTRUCTION DOCUMENT. 

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

1846 rows, 3 columns, the variables are dataset: indicates which dataset the data are from, x: x-values, and y: y-values 

### Exercise 2




```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```



```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3




```{r plot-star, fig.height=3, fig.width=6}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()

```


 
```


```

### Exercise 4


```


```

```{r plot-circle, fig.height=3, fig.width=6}
cirlce_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = cirlce_data, mapping = aes(x = x, y = y)) +
  geom_point()


```

### Exercise 5

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
 geom_point()+
 facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
 theme(legend.position = "none")
```
```{r}
 datasaurus_dozen %>%
 group_by(dataset) %>%
 summarize(r = cor(x, y))
```

